language: php

php:
  - "5.6"
  - "7.0"
  - "7.1"

script: phpunit --configuration tests/phpunit.xml --coverage-text

matrix:
  include:
    - php: 5.2
        dist: precise
    - php: 5.3
        dist: precise